[build]
  publish = "build/"
  command = "npm run build"

[[redirects]]
  from = "/api/v1"
  to = "https://gov-db.makerfoundation.com/api/v1"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_GRAPH_HTTP = "https://gateway.thegraph.com/api/ad06bcb2eee99ff1598a4d8634e1adbe/subgraphs/id/CcR73ZB82xbUZwZg9hSD4XUNhWjRDYt375KawRQhd6h8"
  REACT_APP_GRAPH_WS = "wss://gateway.thegraph.com/api/ad06bcb2eee99ff1598a4d8634e1adbe/subgraphs/id/CcR73ZB82xbUZwZg9hSD4XUNhWjRDYt375KawRQhd6h8"
  REACT_APP_MKR_GRAPH_HTTP='https://gateway.thegraph.com/api/ad06bcb2eee99ff1598a4d8634e1adbe/subgraphs/id/7aLegv47P5Y1EGYduQwmqVznXMy7HchJPkRM1rrzPrKV'
  REACT_APP_GOV_DB_HTTP='/api/v1'
  REACT_APP_ETHERSCAN_API_KEY='XQ2QTEM7H4KX7AQTE9JWXD3HWTTZ46TTU9'
  REACT_APP_LAST_CACHE_UPDATE='1591122639'
  REACT_APP_CACHE_FORCE_UPDATE='1591122639'
  REACT_APP_HOME_DATA_TTL='5'

[context.branch-deploy.environment]
  REACT_APP_GRAPH_HTTP = "https://gateway.thegraph.com/api/ad06bcb2eee99ff1598a4d8634e1adbe/subgraphs/id/CcR73ZB82xbUZwZg9hSD4XUNhWjRDYt375KawRQhd6h8"
  REACT_APP_GRAPH_WS = "wss://gateway.thegraph.com/api/ad06bcb2eee99ff1598a4d8634e1adbe/subgraphs/id/CcR73ZB82xbUZwZg9hSD4XUNhWjRDYt375KawRQhd6h8"
  REACT_APP_MKR_GRAPH_HTTP='https://gateway.thegraph.com/api/ad06bcb2eee99ff1598a4d8634e1adbe/subgraphs/id/7aLegv47P5Y1EGYduQwmqVznXMy7HchJPkRM1rrzPrKV'
  REACT_APP_GOV_DB_HTTP='/api/v1'
  REACT_APP_ETHERSCAN_API_KEY='XQ2QTEM7H4KX7AQTE9JWXD3HWTTZ46TTU9'
  REACT_APP_LAST_CACHE_UPDATE='1591122639'
  REACT_APP_CACHE_FORCE_UPDATE='1591122639'
  REACT_APP_HOME_DATA_TTL='5'

[context.deploy-preview.environment]
  REACT_APP_GRAPH_HTTP = "https://gateway.thegraph.com/api/ad06bcb2eee99ff1598a4d8634e1adbe/subgraphs/id/CcR73ZB82xbUZwZg9hSD4XUNhWjRDYt375KawRQhd6h8"
  REACT_APP_GRAPH_WS = "wss://gateway.thegraph.com/api/ad06bcb2eee99ff1598a4d8634e1adbe/subgraphs/id/CcR73ZB82xbUZwZg9hSD4XUNhWjRDYt375KawRQhd6h8"
  REACT_APP_MKR_GRAPH_HTTP='https://gateway.thegraph.com/api/ad06bcb2eee99ff1598a4d8634e1adbe/subgraphs/id/7aLegv47P5Y1EGYduQwmqVznXMy7HchJPkRM1rrzPrKV'
  REACT_APP_GOV_DB_HTTP='/api/v1'
  REACT_APP_ETHERSCAN_API_KEY='XQ2QTEM7H4KX7AQTE9JWXD3HWTTZ46TTU9'
  REACT_APP_LAST_CACHE_UPDATE='1591122639'
  REACT_APP_CACHE_FORCE_UPDATE='1591122639'
  REACT_APP_HOME_DATA_TTL='5'
